version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper:3.5
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3.5
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  mysql:
    image: mysql:8.0.4
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'vaxidrez'
      MYSQL_PASSWORD: 'VaxiDrez2005$$'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3305:3305'
    expose:
      - '3305'
    volumes:
      - mysql_data:/var/lib/mysql
  mongodb:
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "VaxiDrez2005$$"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
networks:
  default:
    name: bankingNetwork
